In [32]:
#1、创建布尔类型数组
import numpy as np
bo = np.full(5,True,dtype = bool)
bo =np.ones(2,dtype=bool)
print(bo)


[ True  True]


In [12]:
#2、输出满足条件的数组，且不改变原数组的数据
arr = np.arange(10)
out = np.where((arr % 2 == 1),-1,arr)
print("arr = ",arr)
print("out = ",out)

arr =  [0 1 2 3 4 5 6 7 8 9]
out =  [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [15]:
#3、数组叠加
a = np.array([1,2,3])
b = np.array([4,5,6])
vsum = np.vstack([a,b])  #列叠加
hsum = np.hstack([a,b])  #行叠加
print(vsum)
print(hsum)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [17]:
#4、获取数组的公共项和相差项
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a,b)  #a、b公共部分
diff = np.setdiff1d(b,a) #b - a
print(common)
print(diff)

[2 4]
[ 7  8  9 10]


In [20]:
#5、交换二维数组的行和列
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]  #交换列
arr[[1,0,2],:]  #交换行

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [44]:
#6、鸢尾属植物数据集处理
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=",",dtype=object)
iris_ld =  np.genfromtxt(url,delimiter=",",dtype=None)
#print(iris_ld[:3])
species = np.array([row[4] for row in iris_ld])
#print(species[:5])
iris_2d = np.genfromtxt(url,delimiter=",",dtype=float,usecols=[0,1,2,3])
#print(iris_2d[:4])
sepallength = np.genfromtxt(url,delimiter=",",dtype=float,usecols=[0])
Smax,Smin = sepallength.max(),sepallength.min()
S = (sepallength-Smin)/(Smax-Smin)
iris_2d[np.random.randint(150,size=20),np.random.randint(4,size=20)] = np.nan
#print(np.isnan(iris_2d[:,0]).sum())
#print(np.where(np.isnan(iris_2d[:,0])))
#condition = (iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)
#iris_2d[condition]
#iris_2d[np.sum(np.isnan(iris_2d),axis=1) == 0][:5]
np.isnan(iris_2d).any()

F:\python\Anaconda\lib\site-packages\ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


True